$hypr_config_dir = ~/.config/hypr
$hyprland_config_dir = $hypr_config_dir/hyprland
source = $hyprland_config_dir/envvars.conf
source = $hyprland_config_dir/autostart.conf
source = $hyprland_config_dir/general.conf
source = $hyprland_config_dir/rules.conf
source = $hyprland_config_dir/bindings.conf
source = $hyprland_config_dir/local.conf
