font_family monospace
# {% `font_size ${data.appearance.font.size}${"\n"}` %}
font_size 12
# {% end %}
remember_window_size false
background_opacity 0.9
background_blur 1
# {% `shell ${data.default_apps.interactive_shell}${"\n"}` %}
shell fish
# {% end %}

map page_up   scroll_page_up
map page_down scroll_page_down

cursor            #c9d4c3 # {< replace_color(data.appearance.colors.text) >}
cursor_text_color #18210e # {< replace_color(data.appearance.colors.base) >}
url_color         #90c483 # {< replace_color(data.appearance.colors.fg_accent_1) >}

active_tab_foreground   #18210e # {< replace_color(data.appearance.colors.base) >}
active_tab_background   #c9d4c3 # {< replace_color(data.appearance.colors.text) >}
inactive_tab_foreground #18210e # {< replace_color(data.appearance.colors.base) >}
inactive_tab_background #778071 # {< replace_color(data.appearance.colors.muted) >}

foreground #c9d4c3 # {< replace_color(data.appearance.colors.text) >}
background #18210e # {< replace_color(data.appearance.colors.base) >}
selection_foreground #18210e # {< replace_color(data.appearance.colors.base) >}
selection_background #c9d4c3 # {< replace_color(data.appearance.colors.text) >}

# black
color0 #18210e # {< replace_color(data.appearance.colors.black) >}
color8 #3b4232 # {< replace_color(lighten(data.appearance.colors.black, 15)) >}
# red
color1 #e69f8a # {< replace_color(data.appearance.colors.fg_red) >}
color9 #eaad9c # {< replace_color(lighten(data.appearance.colors.fg_red, 15)) >}
# green
color2  #90c483 # {< replace_color(data.appearance.colors.fg_green) >}
color10 #a1cd96 # {< replace_color(lighten(data.appearance.colors.fg_green, 15)) >}
# yellow
color3  #c7b269 # {< replace_color(data.appearance.colors.fg_yellow) >}
color11 #cfbe80 # {< replace_color(lighten(data.appearance.colors.fg_yellow, 15)) >}
# blue
color4  #b1aed5 # {< replace_color(data.appearance.colors.fg_blue) >}
color12 #bdbadb # {< replace_color(lighten(data.appearance.colors.fg_blue, 15)) >}
# magenta
color5  #beaace # {< replace_color(data.appearance.colors.fg_magenta) >}
color13 #c8b7d5 # {< replace_color(lighten(data.appearance.colors.fg_magenta, 15)) >}
# cyan
color6  #67c7ba # {< replace_color(data.appearance.colors.fg_cyan) >}
color14 #7ecfc4 # {< replace_color(lighten(data.appearance.colors.fg_cyan, 15)) >}
# white
color7  #c9d4c3 # {< replace_color(data.appearance.colors.white) >}
color15 #d1dacc # {< replace_color(lighten(data.appearance.colors.white, 15)) >}

mark1_foreground #90c483 # {< replace_color(data.appearance.colors.fg_accent_1) >}
mark1_background #305426 # {< replace_color(data.appearance.colors.bg_accent_1) >}
mark2_foreground #c7b269 # {< replace_color(data.appearance.colors.fg_accent_2) >}
mark2_background #57480e # {< replace_color(data.appearance.colors.bg_accent_2) >}
mark3_foreground #dca587 # {< replace_color(data.appearance.colors.fg_accent_3) >}
mark3_background #62402e # {< replace_color(data.appearance.colors.bg_accent_3) >}
