#!/bin/sh

_pkgs=(
    'base{,-devel}' 'linux{,-headers}' '{linux,sof}-firmware'
    'btrfs-progs' 'efibootmgr' 'grub' 'zram-generator' 'pacman-contrib' 'yay' 'rebuild-detector'
    'linux-cachyos-bore{,-headers}' 'cachyos-{keyring,{v3-,v4-,}mirrorlist,rate-mirrors}'

    # network & bluetooth
    'networkmanager' 'openssh' 'zapret2' 'cloudflare-warp-bin' 'bluez{,-utils}'

    # audio (pipewire)
    'rtkit' 'pipewire{,-audio,-alsa,-pulse,-jack}' 'wireplumber'

    # graphics drivers
    'mesa{,-utils}' 'vulkan-{icd-loader,tools,radeon}' 'nvidia-{open-dkms,utils,prime}'
    'lib32-{mesa,vulkan-{icd-loader,radeon},nvidia-utils}'

    # window manager (niri)
    'niri' 'xwayland-satellite' 'xdg-desktop-portal-{gtk,wlr}' 'quickshell'

    # looks & feel
    'nwg-look' 'qt{6,5}ct-kde' 'kvantum{,-qt5}'
    'noto-fonts{,-cjk,-emoji,-extra}' 'ttf-{liberation,0xproto-nerd}'
    'bibata-cursor-theme-bin' 'papirus-icon-theme'
    'materia-{gtk-theme,kde}' 'kvantum-theme-materia'
    'fcitx5{,-configtool,-bamboo}'

    # shell & cli tools
    'bash{,-completion}' 'fish' 'starship' '{lazy,}git{,-lfs}' 'yolk-bin' 'thaimeleon'
    'neovim' 'tree-sitter-cli' 'less' 'tree' 'fzf' 'ripgrep' 'jq' 'trash-cli' '{namcap,devtools,aurpublish}'
    'xdg-{utils,user-dirs,sound}' 'dex' 'power-profiles-daemon' 'brightnessctl' 'playerctl' 'wl-clipboard'
    'gdu' 'ffmpeg' 'imagemagick' 'btop' 'nvtop'
    ## development
    'bash-language-server' 'fish-lsp' 'vim-language-server' 'lua{,-language-server}'
    'python{,-pip,-lsp-server}' '{gcc,clang,cmake}' '{odin,ols}' 'rust'

    # gui apps
    'kitty' 'firefox' '{thunar{,-archive-plugin,-volman},gvfs,tumbler,ffmpegthumbnailer}' 'tuxmanager'
    '{xarchiver,tar,7zip,unrar}' 'imv' 'vlc{,-plugins-all}' 'keepassxc' 'qbittorrent'
    'vesktop' 'easyeffects' 'selectdefaultapplication-git' 'zeal'
    ## gaming
    'steam' 'gamescope' 'gamemode' '{lib32-,}mangohud' 'protonplus' 'pince'
)

eval echo "${_pkgs[@]}"
