#!/bin/sh

_pkgs=(
    'base{,-devel}' 'linux{,-headers}' '{linux,sof}-firmware'
    'btrfs-progs' 'efibootmgr' 'grub' 'zram-generator' 'pacman-contrib' 'yay'
    'linux-cachyos-bore{,-headers}' 'cachyos-{keyring,{v3-,v4-,}mirrorlist,rate-mirrors}'

    # network & bluetooth
    'networkmanager' 'openssh' 'bluez{,-utils}'

    # audio (pipewire)
    'rtkit' 'pipewire{,-audio,-alsa,-pulse,-jack}' 'wireplumber'

    # graphics drivers
    'mesa{,-utils}' 'vulkan-{icd-loader,tools}'
    'vulkan-radeon' 'nvidia-{open-dkms,utils,prime}'
    lib32-{mesa,vulkan-icd-loader,vulkan-radeon,nvidia-utils}

    # window manager (niri)
    'niri' 'xwayland-satellite' 'xdg-desktop-portal-{gtk,wlr}' 'xdg-{utils,user-dirs}' 'dex'
    'quickshell' 'cliphist' 'brightnessctl' 'playerctl'

    # looks & feel
    'nwg-look' 'qt{6,5}ct-kde' 'kvantum{,-qt5}'
    'noto-fonts{,-cjk,-emoji,-extra}' 'ttf-{liberation,0xproto-nerd}'
    'bibata-cursor-theme-bin' 'papirus-icon-theme'
    'materia-{gtk-theme,kde}' 'kvantum-theme-materia'
    'fcitx5{,-configtool,-bamboo}'

    # shell & cli tools
    'bash{,-completion}' 'fish' 'starship' 'fzf' 'git' 'lazygit' 'chezmoi'
    'helix' 'less' 'tree' 'jq' 'trash-cli' 'btop' 'nvtop'

    # gui apps
    'kitty' 'firefox' '{pcmanfm-qt,gvfs,lxqt-archiver,7zip}'
    'imv' 'vlc{,-plugins-all}' 'code' 'vesktop' 'easyeffects'
    '{steam,gamemode,protonup-qt,pince}'
    'selectdefaultapplication-git'

    # developments
    '{gcc,clang,cmake,xmake}' 'python{,-pip}' 'odin' 'rust'
)

eval echo "${_pkgs[@]}"
