#!/bin/sh

_pkgs=(
    'base'
    'base-devel'
    'linux'
    'linux-headers'
    'linux-cachyos-bore'
    'linux-cachyos-bore-headers'
    'linux-firmware'
    'sof-firmware'
    'btrfs-progs'
    'efibootmgr'
    'grub'
    'zram-generator'
    'yay'
    'pacman-contrib'
    'cachyos-keyring'
    'cachyos-mirrorlist'
    'cachyos-v3-mirrorlist'
    'cachyos-v4-mirrorlist'
    'cachyos-rate-mirrors'

    # network
    'networkmanager'

    # audio
    'rtkit'
    'pipewire'
    'pipewire-audio'
    'pipewire-alsa'
    'pipewire-pulse'
    'pipewire-jack'
    'wireplumber'

    # bluetooth
    'bluez'
    'bluez-utils'

    # graphics
    'mesa'
    'mesa-utils'
    'vulkan-icd-loader'
    'vulkan-tools'
    ## amd
    'vulkan-radeon'
    ## nvidia
    'nvidia-open-dkms'
    'nvidia-utils'
    'nvidia-prime'

    # hyprland
    'hyprland'
    'xdg-desktop-portal-hyprland'
    'xdg-desktop-portal-gtk'
    'qt6-wayland'
    'qt5-wayland'
    'brightnessctl' ## hyprland - monitor brightness
    'playerctl'     ## hyprland - mpris controller
    'grimblast-git' ## hyprland - screenshot
    'xorg-xrdb'     ## hyprland - x cursor
    'jq'            ## hyprland - JSON utils
    'quickshell' # desktop shell
    'cliphist'   ## quickshell - clipboard manager

    # xdg
    'xdg-utils'
    'xdg-user-dirs'

    # fonts
    'noto-fonts'
    'noto-fonts-cjk'
    'noto-fonts-emoji'
    'noto-fonts-extra'
    'ttf-liberation'
    'ttf-0xproto-nerd'

    # icons & color schemes
    'bibata-cursor-theme-bin'
    'papirus-icon-theme'
    'materia-gtk-theme'
    'materia-kde'
    'kvantum-theme-materia'

    # theme manage
    'nwg-look'
    'qt6ct-kde'
    'qt5ct-kde'
    'kvantum'
    'kvantum-qt5'

    # ime
    'fcitx5'
    'fcitx5-configtool' ## fcitx5 - config tool
    'fcitx5-bamboo'     ## fcitx5 - Vietnamese IME

    # shells
    'fish'
    'starship'
    'fzf'

    # vcs
    'git'
    'openssh'

    # cli
    'helix' # editor
    'less'  # pager
    'tree'
    'trash-cli'
    'lazygit' # git
    'chezmoi' # dotfiles
    'btop'  # resource manager
    'nvtop' # resource manager

    # gui apps
    'kitty'   # terminal
    'firefox' # browser
    'code'    # editor
    'thunar'                   # file manager
    'gvfs'                     ## thunar - trash support, mounting with udisk and remote filesystems
    'thunar-archive-plugin'    ## thunar - archive creation and extraction
    'thunar-media-tags-plugin' ## thunar - view/edit ID3/OGG tags
    'thunar-volman'            ## thunar - removable device management
    'tumbler'                  ## thunar - thumbnail previews
    'ffmpegthumbnailer'        ## thunar - video thumbnails
    'ark'        # archiving and compression
    '7zip'       ## ark - 7Z format support
    'unarchiver' ## ark - RAR format support
    'unrar'      ## ark - RAR decompression support
    'imv'             # image viewer
    'vlc'             # media player
    'vlc-plugins-all' ## vlc - all plugins
    'easyeffects' # audio effects
    'vesktop' # discord

    # gaming
    'steam'
    'lib32-vulkan-radeon' ## steam - lib32-vulkan-driver
    'lib32-nvidia-utils'  ## steam - lib32-vulkan-driver
    'gamemode'
    'protonup-qt'
    'pince'

    # developments
    ## c/cpp
    'gcc'
    'clang'
    'cmake'
    'xmake'
    ## python
    'python'
    'python-pip'
    ## odin
    'odin'
    ## rust
    'rust'
)
echo "${_pkgs[@]}"
