foreground #d9d2d5 # {< rcol(colors.text) >}
background #27262a # {< rcol(colors.base) >}
selection_foreground #27262a # {< rcol(colors.base) >}
selection_background #d9d2d5 # {< rcol(colors.text) >}

color0  #27262a # {< rcol(colors.base) >}
color8  #504d54 # {< rcol(colors.overlay) >}
color1  #b16a72 # {< rcol(colors.rg_red) >}
color9  #f19ca4 # {< rcol(colors.fg_red) >}
color2  #78895b # {< rcol(colors.rg_green) >}
color10 #acc189 # {< rcol(colors.fg_green) >}
color3  #a2784d # {< rcol(colors.rg_yellow) >}
color11 #dfac79 # {< rcol(colors.fg_yellow) >}
color4  #8178b6 # {< rcol(colors.rg_blue) >}
color12 #b6acf6 # {< rcol(colors.fg_blue) >}
color5  #9371ac # {< rcol(colors.rg_magenta) >}
color13 #cca4ea # {< rcol(colors.fg_magenta) >}
color6  #4d9085 # {< rcol(colors.rg_cyan) >}
color14 #79c9bb # {< rcol(colors.fg_cyan) >}
color7  #bdb4bb # {< rcol(colors.subtext) >}
color15 #d9d2d5 # {< rcol(colors.text) >}
