# {# rr("font_family.*", `font_family ${theme.font_mono.name}`) #}
font_family monospace
# {# rnum(theme.font_mono.size) #}
font_size 12

remember_window_size false
background_opacity   0.85
background_blur      1
shell                fish

map page_up   scroll_page_up
map page_down scroll_page_down

cursor            #b5bdb0 // {< rcol(theme.colors.text) >}
cursor_text_color #141a10 // {< rcol(theme.colors.base) >}
url_color         #74a467 // {< rcol(theme.colors.fg_accent_1) >}

active_tab_foreground   #141a10 // {< rcol(theme.colors.base) >}
active_tab_background   #b5bdb0 // {< rcol(theme.colors.text) >}
inactive_tab_foreground #141a10 // {< rcol(theme.colors.base) >}
inactive_tab_background #6d7468 // {< rcol(theme.colors.muted) >}

foreground #b5bdb0 // {< rcol(theme.colors.text) >}
background #141a10 // {< rcol(theme.colors.base) >}
selection_foreground #141a10 // {< rcol(theme.colors.base) >}
selection_background #b5bdb0 // {< rcol(theme.colors.text) >}

# black
color0 #141a10 // {< rcol(theme.colors.black) >}
color8 #434840 // {< rcol(lighten(theme.colors.black, 20)) >}
# red
color1 #956354 // {< rcol(theme.colors.rg_red) >}
color9 #bf8473 // {< rcol(theme.colors.fg_red) >}
# green
color2  #537e48 // {< rcol(theme.colors.rg_green) >}
color10 #74a467 // {< rcol(theme.colors.fg_green) >}
# yellow
color3  #82702e // {< rcol(theme.colors.rg_yellow) >}
color11 #a8944b // {< rcol(theme.colors.fg_yellow) >}
# blue
color4  #706c90 // {< rcol(theme.colors.rg_blue) >}
color12 #938fba // {< rcol(theme.colors.fg_blue) >}
# magenta
color5  #7b6989 // {< rcol(theme.colors.rg_magenta) >}
color13 #a08bb2 // {< rcol(theme.colors.fg_magenta) >}
# cyan
color6  #268177 // {< rcol(theme.colors.rg_cyan) >}
color14 #46a79c // {< rcol(theme.colors.fg_cyan) >}
# white
color7  #b5bdb0 // {< rcol(theme.colors.white) >}
color15 #c4cac0 // {< rcol(lighten(theme.colors.white, 20)) >}

mark1_foreground #74a467 // {< rcol(theme.colors.fg_accent_1) >}
mark1_background #325528 // {< rcol(theme.colors.bg_accent_1) >}
mark2_foreground #a8944b // {< rcol(theme.colors.fg_accent_2) >}
mark2_background #584a10 // {< rcol(theme.colors.bg_accent_2) >}
mark3_foreground #be8668 // {< rcol(theme.colors.fg_accent_3) >}
mark3_background #65412c // {< rcol(theme.colors.bg_accent_3) >}
