#!/usr/bin/env fish

if test -n "$XDG_CONFIG_HOME"
    set xdg_cfg_home $XDG_CONFIG_HOME
else
    set xdg_cfg_home "$HOME/.config"
end

set gtk_cfg_file "$xdg_cfg_home/gtk-4.0/settings.ini"
test -f "$gtk_cfg_file"; or set gtk_cfg_file "$xdg_cfg_home/gtk-3.0/settings.ini"
test -f "$gtk_cfg_file"; or exit 1

function get_gtk_value -a key -V gtk_cfg_file
    set -l line (grep "$key" "$gtk_cfg_file")
    test -n "$line"; and string trim (string split -m1 '=' $line)[2]
end

hyprctl setcursor "$(get_gtk_value gtk-cursor-theme-name)" "$(get_gtk_value gtk-cursor-theme-size)"
