#!/usr/bin/env fish

set -l wallpaper_dir "$(xdg-user-dir PICTURES)/wallpapers"
mkdir -p "$wallpaper_dir"

set -l all_wallpapers (
    find "$wallpaper_dir" -type f \( \
        -iname "*.png"  -o           \
        -iname "*.jpg"  -o           \
        -iname "*.jpeg" -o           \
        -iname "*.jpe"  -o           \
        -iname "*.jxl"  -o           \
        -iname "*.webp"              \
    \)
)
test (count $all_wallpapers) -gt 0 || exit

# hyprpaper v0.8 can no longer query current wallpaper
#set -l current_wallpaper (
#    hyprctl hyprpaper listactive \
#    | head -n 1                  \
#    | string replace -r '\s*=\s*' ''
#)

#set -l new_wallpaper ""
#while true
#    set new_wallpaper (random choice $all_wallpapers)
#    test "$new_wallpaper" != "$current_wallpaper" && break
#end

#hyprctl hyprpaper reload ,"$new_wallpaper"

set -l new_wallpaper (random choice $all_wallpapers)
hyprctl hyprpaper wallpaper ",$new_wallpaper"
