#!/usr/bin/env fish

set -l wallpaper_dir "$(xdg-user-dir PICTURES)/wallpapers"
mkdir -p "$wallpaper_dir"

set -l all_wallpapers (
    find "$wallpaper_dir" -type f \( \
        -iname "*.png"  -o           \
        -iname "*.jpg"  -o           \
        -iname "*.jpeg" -o           \
        -iname "*.jpe"  -o           \
        -iname "*.jxl"  -o           \
        -iname "*.webp"              \
    \)
)
test (count $all_wallpapers) -gt 0; or exit

set -l new_wallpaper (random choice $all_wallpapers)
hyprctl hyprpaper wallpaper ",$new_wallpaper"
matugen image "$new_wallpaper"
