legacy_layout=0
position=top-left
hud_no_margin
background_alpha=0.5
alpha=1.0
font_size=24
text_outline

toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11
toggle_preset=Shift_R+F10
toggle_fps_limit=Shift_L+F1
toggle_logging=Shift_L+F2
reload_cfg=Shift_L+F4
upload_log=Shift_L+F3
reset_fps_metrics=Shift_R+F9

preset=1,2,3
