$mod = SUPER

bind = CTRL+ALT, DELETE, exit

# workspaces
bind = $mod, GRAVE, togglespecialworkspace
bind = $mod, 1,     workspace, 1
bind = $mod, 2,     workspace, 2
bind = $mod, 3,     workspace, 3
bind = $mod, 4,     workspace, 4
bind = $mod, 5,     workspace, 5
bind = $mod, 6,     workspace, 6
bind = $mod, 7,     workspace, 7
bind = $mod, 8,     workspace, 8
bind = $mod, 9,     workspace, 9
bind = $mod, 0,     workspace, 10
bind = $mod, PRIOR, workspace, r-1
bind = $mod, NEXT,  workspace, r+1
gesture = 3, vertical, workspace

# windows
#//
bind = $mod, ESCAPE,   killactive
bind = ALT, F4,        killactive
bind = ALT, TAB,       cyclenext
bind = ALT, TAB,       alterzorder, top
bind = ALT+SHIFT, TAB, cyclenext, prev
bind = ALT+SHIFT, TAB, alterzorder, top
bind = $mod, F,        fullscreen, 0
bind = $mod, D,        fullscreen, 1
bind = $mod, V,        togglefloating
bind = $mod, S,        pin
#//
bind = $mod, H,      movefocus, l
bind = $mod, J,      movefocus, d
bind = $mod, K,      movefocus, u
bind = $mod, L,      movefocus, r
bind = $mod, LEFT,   movefocus, l
bind = $mod, DOWN,   movefocus, d
bind = $mod, UP,     movefocus, u
bind = $mod, RIGHT,  movefocus, r
bind = $mod, COMMA,  layoutmsg, colresize -conf
bind = $mod, PERIOD, layoutmsg, colresize +conf
bind = $mod, C,      layoutmsg, promote
#//
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
#//
bind = $mod+SHIFT, H,     swapwindow, l
bind = $mod+SHIFT, J,     swapwindow, d
bind = $mod+SHIFT, K,     swapwindow, u
bind = $mod+SHIFT, L,     swapwindow, r
bind = $mod+SHIFT, LEFT,  swapwindow, l
bind = $mod+SHIFT, DOWN,  swapwindow, d
bind = $mod+SHIFT, UP,    swapwindow, u
bind = $mod+SHIFT, RIGHT, swapwindow, r
#//
bind = $mod+SHIFT, GRAVE, movetoworkspace, special
bind = $mod+SHIFT, 1,     movetoworkspace, 1
bind = $mod+SHIFT, 2,     movetoworkspace, 2
bind = $mod+SHIFT, 3,     movetoworkspace, 3
bind = $mod+SHIFT, 4,     movetoworkspace, 4
bind = $mod+SHIFT, 5,     movetoworkspace, 5
bind = $mod+SHIFT, 6,     movetoworkspace, 6
bind = $mod+SHIFT, 7,     movetoworkspace, 7
bind = $mod+SHIFT, 8,     movetoworkspace, 8
bind = $mod+SHIFT, 9,     movetoworkspace, 9
bind = $mod+SHIFT, 0,     movetoworkspace, 10
bind = $mod+SHIFT, PRIOR, movetoworkspace, r-1
bind = $mod+SHIFT, NEXT,  movetoworkspace, r+1

# apps
bind = $mod, T, exec, $hypr_app_terminal
bind = $mod, E, exec, $hypr_app_file_manager
bind = $mod, B, exec, $hypr_app_browser

# media
bindel = ,XF86MonBrightnessUp,   exec, brightnessctl --class=backlight set 2%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl --class=backlight set 2%-
bindel = ,XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ -l 1
bindel = ,XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindl  = ,XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl  = ,XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = ,XF86AudioPlay,         exec, playerctl play-pause
bindl  = ,XF86AudioStop,         exec, playerctl stop
bindl  = ,XF86AudioPrev,         exec, playerctl previous
bindl  = ,XF86AudioNext,         exec, playerctl next

# misc
bind  = $mod, mouse_down, exec, $hyprland_config_dir/scripts/magnifier +0.2
bind  = $mod, mouse_up,   exec, $hyprland_config_dir/scripts/magnifier -0.2
binde = $mod, EQUAL,      exec, $hyprland_config_dir/scripts/magnifier +0.2
binde = $mod, MINUS,      exec, $hyprland_config_dir/scripts/magnifier -0.2
