windowrule = match:class .*,      immediate on
windowrule = match:xwayland true, no_blur on
layerrule  = match:namespace .*,  xray on, ignore_alpha 0
workspace  = f[1],                gapsout:0, rounding:false

# specifics
windowrule = float on,                       match:class ^(xdg-desktop-portal-gtk|hyprland-share-picker)$
windowrule = float on,                       match:class ^thunar$, match:title negative:.* - Thunar$
windowrule = float on,                       match:class ^xarchiver$, match:title ^Extract files$
windowrule = float on, pin on, size 640 360, match:class ^firefox$, match:title ^Picture-in-Picture$
