[Settings]
# {# replace_quoted(if data.appearance.colors.is_light_theme == "true" { data.appearance.gtk.theme } else { data.appearance.gtk.theme_dark }) #}
gtk-theme-name="adw-gtk3-dark"
# {# replace_quoted(if data.appearance.colors.is_light_theme == "true" { data.appearance.icon.theme } else { data.appearance.icon.theme_dark }) #}
gtk-icon-theme-name="Papirus-Dark"
# {# replace_quoted(`${data.appearance.font.name} ${data.appearance.font.size}`) #}
gtk-font-name="sans 12"
# {# replace_quoted(data.appearance.xcursor.theme) #}
gtk-cursor-theme-name="Bibata-Modern-Ice"
# {# replace_value(data.appearance.xcursor.size.to_string()) #}
gtk-cursor-theme-size=24
gtk-button-images=1
gtk-menu-images=1
# {# replace_value(if data.appearance.colors.is_light_theme == "true" { "0" } else { "1" }) #}
gtk-application-prefer-dark-theme=1
